export const pics = [
  "844",
  "scary_alien_head_cartoon_vector",
  "1273",
  "angry_red_octopus_vector_logo",
  "scary_pumpkin_head_halloween_vector",
  "1276",
  "ape_cartoon_with_crown_and_sunglasses",
  "skeleton_hand_holding_rose_vector",
  "1283",
  "balinese_barong_mask_vector_illustration",
  "skull_anubis_egypt_vector_illustration",
  "1286",
  "black_cat_head_vector_illustration",
  "skull_bikers_wearing_helmet_illustration",
  "1363",
  "bulldog_cartoon_wearing_gold_chain_vector",
  "skull_with_red_rose_vector",
  "1366",
  "creepy_clown_head_vector_logo",
  "smoking_skull_wearing_bucket_hat_vector",
  "1415",
  "gangster_dog_character_vector_illustration",
  "sugar_skull_tattoo_style_with_roses_illustration",
  "1507",
  "heart_grenade_vector_logo_illustration",
  "sugarskull_with_roses_vector_ornament",
  "1508",
  "1535",
  "zombie_biker_head_vector_logo",
  "1539",
  "red_devil_face_vector_logo",
  "red_rose_flower_vector_logo",
];

export const tatData = [
  {
    img: "angry_red_octopus",
    name: "Angry Red Octopus",
    tags: "animal",
    views: "8704",
    firstOrder: true,
    price: "3699",
    author: "Yetty Tice",
    votes: "89",
    id: "534998",
  },
  {
    img: "heart_grenade",
    name: "Heart Grenade",
    tags: "heart",
    views: "9642",
    firstOrder: true,
    price: "2050",
    author: "Lauryn Haldas",
    votes: "92",
    id: "167740",
  },
  {
    img: "skull_girl",
    name: "Skull Girl",
    tags: "face,skull",
    views: "4952",
    firstOrder: false,
    price: "2050",
    author: "Randa Ade",
    votes: "8",
    id: "497128",
  },
  {
    img: "ape_cartoon_with_crown_and_sunglasses",
    name: "Ape Cartoon With Crown And Sunglasses",
    tags: "face,animal",
    views: "6037",
    firstOrder: true,
    price: "2050",
    author: "Rivalee Bebe",
    votes: "80",
    id: "254471",
  },
  {
    img: "knives_and_moths",
    name: "Knives And Moths",
    tags: "knive",
    views: "10796",
    firstOrder: true,
    price: "3699",
    author: "Hallie Roumell",
    votes: "15",
    id: "299777",
  },
  {
    img: "skull_with_red_rose",
    name: "Skull With Red Rose",
    tags: "flower,skull",
    views: "8587",
    firstOrder: false,
    price: "3699",
    author: "Courtnay Septima",
    votes: "92",
    id: "350153",
  },
  {
    img: "balinese_barong_mask",
    name: "Balinese Barong Mask",
    tags: "face",
    views: "7558",
    firstOrder: true,
    price: "2050",
    author: "Ardenia Allys",
    votes: "75",
    id: "494364",
  },
  {
    img: "lucky_thirteen",
    name: "Lucky Thirteen",
    tags: "face",
    views: "12253",
    firstOrder: true,
    price: "1599",
    author: "Raquela Aaberg",
    votes: "96",
    id: "517653",
  },
  {
    img: "skulls_and_roses",
    name: "Skulls And Roses",
    tags: "flower,skull",
    views: "4265",
    firstOrder: false,
    price: "1599",
    author: "Basia Beniamino",
    votes: "95",
    id: "156212",
  },
  {
    img: "black_cat_head",
    name: "Black Cat Head",
    tags: "animal",
    views: "5966",
    firstOrder: true,
    price: "3699",
    author: "Gale Parsaye",
    votes: "71",
    id: "301910",
  },
  {
    img: "red_devil_face",
    name: "Red Devil Face",
    tags: "face",
    views: "8735",
    firstOrder: true,
    price: "3699",
    author: "Marti Lia",
    votes: "70",
    id: "346148",
  },
  {
    img: "smoking_skull_wearing_bucket_hat",
    name: "Smoking Skull Wearing Bucket Hat",
    tags: "face,skull",
    views: "10407",
    firstOrder: false,
    price: "1599",
    author: "Elfreda Judye",
    votes: "43",
    id: "306462",
  },
  {
    img: "bulldog_cartoon_wearing_gold_chain",
    name: "Bulldog Cartoon Wearing Gold Chain",
    tags: "face,animal",
    views: "9983",
    firstOrder: false,
    price: "2050",
    author: "Arlena Corabella",
    votes: "52",
    id: "405262",
  },
  {
    img: "red_rose_flower",
    name: "Red Rose Flower",
    tags: "flower",
    views: "8839",
    firstOrder: false,
    price: "1599",
    author: "Violet Deny",
    votes: "85",
    id: "242452",
  },
  {
    img: "snake",
    name: "Snake",
    tags: "animal",
    views: "11277",
    firstOrder: false,
    price: "3699",
    author: "Cindelyn Alcott",
    votes: "19",
    id: "490416",
  },
  {
    img: "creepy_clown_head",
    name: "Creepy Clown Head",
    tags: "face",
    views: "8393",
    firstOrder: true,
    price: "1599",
    author: "Katuscha Bari",
    votes: "3",
    id: "232371",
  },
  {
    img: "roses_parlour",
    name: "Roses Parlour",
    tags: "flower",
    views: "10240",
    firstOrder: true,
    price: "3699",
    author: "Susette Romelda",
    votes: "42",
    id: "293044",
  },
  {
    img: "snake_skull",
    name: "Snake Skull",
    tags: "skull,animal",
    views: "9793",
    firstOrder: false,
    price: "3699",
    author: "Mady Nickola",
    votes: "50",
    id: "132160",
  },
  {
    img: "death_cross",
    name: "Death Cross",
    tags: "face,flower",
    views: "10349",
    firstOrder: false,
    price: "3699",
    author: "Ricky Berl",
    votes: "36",
    id: "361950",
  },
  {
    img: "scary_alien_head_cartoon",
    name: "Scary Alien Head Cartoon",
    tags: "face",
    views: "11857",
    firstOrder: false,
    price: "3699",
    author: "Lilith Vastah",
    votes: "11",
    id: "361043",
  },
  {
    img: "sugar_skull_tattoo_style_with_roses",
    name: "Sugar Skull Tattoo Style With Roses",
    tags: "face,flower,skull",
    views: "8337",
    firstOrder: false,
    price: "2050",
    author: "Elmira Roumell",
    votes: "75",
    id: "140477",
  },
  {
    img: "fire_hart",
    name: "Fire Hart",
    tags: "heart",
    views: "9270",
    firstOrder: false,
    price: "1599",
    author: "Kimmy Rodmann",
    votes: "49",
    id: "368702",
  },
  {
    img: "scary_pumpkin_head_halloween",
    name: "Scary Pumpkin Head Halloween",
    tags: "face",
    views: "5290",
    firstOrder: false,
    price: "1599",
    author: "Melisent Brian",
    votes: "84",
    id: "169478",
  },
  {
    img: "sugarskull_with_roses",
    name: "Sugarskull With Roses",
    tags: "face,flower,skull",
    views: "3594",
    firstOrder: false,
    price: "3699",
    author: "Kathy Merat",
    votes: "14",
    id: "515726",
  },
  {
    img: "flower_from_dead",
    name: "Flower From Dead",
    tags: "flower",
    views: "7072",
    firstOrder: true,
    price: "2050",
    author: "Jessamyn Klemperer",
    votes: "21",
    id: "552077",
  },
  {
    img: "skeleton_hand_holding_rose",
    name: "Skeleton Hand Holding Rose",
    tags: "flower",
    views: "8775",
    firstOrder: true,
    price: "1599",
    author: "Natka Jillane",
    votes: "55",
    id: "387653",
  },
  {
    img: "two_wings",
    name: "Two Wings",
    tags: "wings",
    views: "9098",
    firstOrder: true,
    price: "3699",
    author: "Nollie Ophelia",
    votes: "5",
    id: "150886",
  },
  {
    img: "gangster_dog_character",
    name: "Gangster Dog Character",
    tags: "face,animal",
    views: "7103",
    firstOrder: true,
    price: "3699",
    author: "Amalie Stav",
    votes: "4",
    id: "164206",
  },
  {
    img: "skull_anubis_egypt",
    name: "Skull Anubis Egypt",
    tags: "face,skull",
    views: "6794",
    firstOrder: false,
    price: "2050",
    author: "Xylina Lucienne",
    votes: "1",
    id: "346149",
  },
  {
    img: "zombie_biker_head",
    name: "Zombie Biker Head",
    tags: "face",
    views: "8628",
    firstOrder: true,
    price: "3699",
    author: "Alameda Faust",
    votes: "100",
    id: "366049",
  },
  {
    img: "hart_bones",
    name: "Hart Bones",
    tags: "heart",
    views: "8494",
    firstOrder: false,
    price: "1599",
    author: "Jan Land",
    votes: "44",
    id: "220120",
  },
];

// repeat(32, { "views": random(3456, 12345),
// "firstOrder": randomBool(),
// "price": choice(1599,2050,3699),
// "author": firstname() +' '+ lastname(),
// "votes": random(0, 100),
// "id": random(123456, 567890),})
export const cldary = [
  "snake_skull_ftlrvf",
  "two_wings_edgvsb",
  "sugarskull_with_roses_r4re7f",
  "snake_khrpov",
  "zombie_biker_head_w3tupk",
  "sugar_skull_tattoo_style_with_roses_m5zqqx",
  "smoking_skull_wearing_bucket_hat_xqrfhd",
  "skull_with_red_rose_aslcla",
  "skull_girl_jdzrmi",
  "skull_bikers_wearing_helmet_fqqfd6",
  "roses_parlour_sg6yth",
  "skull_anubis_egypt_cbnqvx",
  "skeleton_hand_holding_rose_umkxpf",
  "scary_pumpkin_head_halloween_nvb3li",
  "knives_and_moths_vltcnm",
  "lucky_thirteen_dj2xw2",
  "scary_alien_head_cartoon_tpelcy",
  "red_rose_flower_ekseyp",
  "red_devil_face_h08h1g",
  "flower_from_dead_djrfbb",
  "fire_hart_fhlfgu",
  "gangster_dog_character_blpcln",
  "hart_bones_yubd3c",
  "heart_grenade_qxahuy",
  "death_cross_s2axqr",
  "ape_cartoon_with_crown_and_sunglasses_czltir",
  "black_cat_head_zwq7pz",
  "balinese_barong_mask_u9yaty",
  "bulldog_cartoon_wearing_gold_chain_gh58zk",
  "creepy_clown_head_sh9yxv",
];
